---
- name: Dependent file for Centos6
  yum: name=libselinux-python state=installed
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: checking kibana already installed...
  stat: path=/etc/kibana
  register: kibana

- name: Downloading kibana package ...
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version_rpm }}-x86_64.rpm
    dest: /opt/

- name: Installing kibana ...
  yum:
    name: /opt/kibana-{{ kibana_version_rpm }}-x86_64.rpm
    state: present

- name: Adding kibana configuration file ...
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml

- name: Check if the epel.repo is exists
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: stat_result

- name: install the epel repo rpm
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: stat_result.stat.exists == False

- name: Installing nginx server on Amazon AMI Machine
  yum:
    name: nginx
    state: installed

- name: Enable nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Remove old files...
  file: path=/etc/nginx/conf.d/default.conf state=absent
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Adding nginx configuration file ...
  template: src=default.j2 dest=/etc/nginx/conf.d/kibana.conf

- name: Install passlib (required for writing htpasswd file).
  yum:
    name: python-passlib
    state: present

- name: Create htpasswd file to restrict access to Kibana web interface.
  htpasswd:
    name: "{{ elk_kibana_username }}"
    password: "{{ elk_kibana_password }}"
    path: /etc/nginx/htpasswd.users
  notify:
    - Restart nginx
    - Restart kibana
